/home/ICer/Shared_Folder/System/RTL/ALU/ALU.v
/home/ICer/Shared_Folder/System/RTL/ASYNC_FIFO/DF_SYNC.v
/home/ICer/Shared_Folder/System/RTL/ASYNC_FIFO/FIFO_MEM.v
/home/ICer/Shared_Folder/System/RTL/ASYNC_FIFO/FIFO_RD.v
/home/ICer/Shared_Folder/System/RTL/ASYNC_FIFO/FIFO_TOP.v
/home/ICer/Shared_Folder/System/RTL/ASYNC_FIFO/FIFO_WR.v
/home/ICer/Shared_Folder/System/RTL/Data_Bus_Sync/Data_Bus_Sync.v
/home/ICer/Shared_Folder/System/RTL/I_CLK_DIV/I_CLK_DIV.v
/home/ICer/Shared_Folder/System/RTL/Pulse_Gen/pulse_gen.v
/home/ICer/Shared_Folder/System/RTL/REG_FILE/Reg_File.v
/home/ICer/Shared_Folder/System/RTL/RST_Synchronizer/RST_Sync.v
/home/ICer/Shared_Folder/System/RTL/RX_CLK_DIV_MUX/RX_CLK_DIV_MUX.v
/home/ICer/Shared_Folder/System/RTL/Sys_Ctrl/Sys_Ctrl.v
/home/ICer/Shared_Folder/System/RTL/System_Top/System_Top.v
/home/ICer/Shared_Folder/System/RTL/UART_RX/Deserializer.v
/home/ICer/Shared_Folder/System/RTL/UART_RX/Edge_Bit_Counter.v
/home/ICer/Shared_Folder/System/RTL/UART_RX/Parity_Checker.v
/home/ICer/Shared_Folder/System/RTL/UART_RX/Sampler.v
/home/ICer/Shared_Folder/System/RTL/UART_RX/Start_Checker.v
/home/ICer/Shared_Folder/System/RTL/UART_RX/Stop_Checker.v
/home/ICer/Shared_Folder/System/RTL/UART_RX/UART_RX.v
/home/ICer/Shared_Folder/System/RTL/UART_RX/UART_RX_FSM.sv
/home/ICer/Shared_Folder/System/RTL/UART_TX/MUX_2x1.v
/home/ICer/Shared_Folder/System/RTL/UART_TX/MUX_4x1.v
/home/ICer/Shared_Folder/System/RTL/UART_TX/UART_Parity.v
/home/ICer/Shared_Folder/System/RTL/UART_TX/UART_Serializer.v
/home/ICer/Shared_Folder/System/RTL/UART_TX/UART_TX_FSM.sv
/home/ICer/Shared_Folder/System/RTL/UART_TX/UART_TX_TOP.v
/home/ICer/Shared_Folder/System/RTL/CLK_GATE/CLK_GATE.v

